
-->Insertar Medellín
INSERT INTO "US_NATURAANTIOQUIA"."DEPARTAMENTOS" (NOMBRE_DEPARTAMENTO) VALUES ('Antioquía');

INSERT INTO CIUDADES (ID_DEPARTAMENTO, NOMBRE_CIUDAD)
VALUES (1, 'Medellín');


--  barrios de Medellín
INSERT INTO BARRIOS (ID_DEPARTAMENTO, ID_CIUDAD, NOMBRE_BARRIO)
VALUES (1, 1, 'Popular');

INSERT INTO BARRIOS (ID_DEPARTAMENTO, ID_CIUDAD, NOMBRE_BARRIO)
VALUES (1, 1, 'Santa Cruz');

INSERT INTO BARRIOS (ID_DEPARTAMENTO, ID_CIUDAD, NOMBRE_BARRIO)
VALUES (1, 1, 'Aranjuez');

INSERT INTO BARRIOS (ID_DEPARTAMENTO, ID_CIUDAD, NOMBRE_BARRIO)
VALUES (1, 1, 'Castilla');

INSERT INTO BARRIOS (ID_DEPARTAMENTO, ID_CIUDAD, NOMBRE_BARRIO)
VALUES (1, 1, 'Doce de Octubre');

INSERT INTO BARRIOS (ID_DEPARTAMENTO, ID_CIUDAD, NOMBRE_BARRIO)
VALUES (1, 1, 'Robledo');

INSERT INTO BARRIOS (ID_DEPARTAMENTO, ID_CIUDAD, NOMBRE_BARRIO)
VALUES (1, 1, 'Villa Hermosa');

INSERT INTO BARRIOS (ID_DEPARTAMENTO, ID_CIUDAD, NOMBRE_BARRIO)
VALUES (1, 1, 'Buenos Aires');

INSERT INTO BARRIOS (ID_DEPARTAMENTO, ID_CIUDAD, NOMBRE_BARRIO)
VALUES (1, 1, 'La Candelaria');

INSERT INTO BARRIOS (ID_DEPARTAMENTO, ID_CIUDAD, NOMBRE_BARRIO)
VALUES (1, 1, 'Laureles-Estadio');

INSERT INTO BARRIOS (ID_DEPARTAMENTO, ID_CIUDAD, NOMBRE_BARRIO)
VALUES (1, 1, 'La América');

INSERT INTO BARRIOS (ID_DEPARTAMENTO, ID_CIUDAD, NOMBRE_BARRIO)
VALUES (1, 1, 'San Javier');

INSERT INTO BARRIOS (ID_DEPARTAMENTO, ID_CIUDAD, NOMBRE_BARRIO)
VALUES (1, 1, 'El Poblado');

INSERT INTO BARRIOS (ID_DEPARTAMENTO, ID_CIUDAD, NOMBRE_BARRIO)
VALUES (1, 1, 'Guayabal');

INSERT INTO BARRIOS (ID_DEPARTAMENTO, ID_CIUDAD, NOMBRE_BARRIO)
VALUES (1, 1, 'Belén');
