CREATE TABLE USUARIOS 
(
  DOCUMENTO_USUARIO INTEGER 
, datos_usuario            contacto
, PRIMER_APELLIDO_USUARIO VARCHAR2(50) 
, SEGUNDO_APELLIDO_USUARIO VARCHAR2(50) 
, PASSWORD_USUARIO VARCHAR2(100) 
, FECHA_NACIMIENTO_USUARIO DATE 
, TIPO_DOCUMENTO INTEGER 
, ESTADO_USUARIO INTEGER 
, SEXO_USUARIO INTEGER 
, ROL_USUARIO INTEGER 
)
TABLESPACE ts_naturaantioquia;


ALTER TABLE USUARIOS
ADD CONSTRAINT nn_nombre_usuario_usuarios CHECK ( datos_usuario.nombre IS NOT NULL);

ALTER TABLE USUARIOS
ADD CONSTRAINT nn_primer_apellido_usuario_usuarios CHECK (PRIMER_APELLIDO_USUARIO IS NOT NULL);

ALTER TABLE USUARIOS
ADD CONSTRAINT nn_correo_usuario_usuarios CHECK (datos_usuario.correo IS NOT NULL);

ALTER TABLE USUARIOS
ADD CONSTRAINT nn_password_usuario_usuarios CHECK (PASSWORD_USUARIO IS NOT NULL);

ALTER TABLE USUARIOS
ADD CONSTRAINT nn_fecha_nacimiento_usuario_usuarios CHECK (FECHA_NACIMIENTO_USUARIO IS NOT NULL);

ALTER TABLE USUARIOS
ADD CONSTRAINT nn_celular_usuario_usuarios CHECK (datos_usuario.telefono.movil IS NOT NULL);

ALTER TABLE USUARIOS
ADD CONSTRAINT nn_tipo_documento_usuario_usuarios CHECK (TIPO_DOCUMENTO IS NOT NULL);

ALTER TABLE USUARIOS
ADD CONSTRAINT nn_estado_usuario_usuarios CHECK (ESTADO_USUARIO IS NOT NULL);

ALTER TABLE USUARIOS
ADD CONSTRAINT nn_sexo_usuario_usuarios CHECK (SEXO_USUARIO IS NOT NULL);

ALTER TABLE USUARIOS
ADD CONSTRAINT nn_rol_usuario_usuarios CHECK (ROL_USUARIO IS NOT NULL);

ALTER TABLE USUARIOS
ADD CONSTRAINT pk_documento_usuario_usuarios PRIMARY KEY (DOCUMENTO_USUARIO);

ALTER TABLE USUARIOS
ADD CONSTRAINT uk_correo_usuario UNIQUE (datos_usuario.correo);


ALTER TABLE USUARIOS
ADD CONSTRAINT fk_sexo_usuario_usuarios
FOREIGN KEY (SEXO_USUARIO)
REFERENCES SEXOS(sexo.id);

ALTER TABLE USUARIOS
ADD CONSTRAINT fk_tipo_documento_usuario_usuarios
FOREIGN KEY (TIPO_DOCUMENTO)
REFERENCES TIPOS_DOCUMENTOS(tipo_documento.id);

ALTER TABLE USUARIOS
ADD CONSTRAINT fk_estado_usuario_usuarios
FOREIGN KEY (ESTADO_USUARIO)
REFERENCES ESTADOS_USUARIOS(estado_usuario.id);

ALTER TABLE USUARIOS
ADD CONSTRAINT fk_rol_usuario_usuarios
FOREIGN KEY (ROL_USUARIO)
REFERENCES ROLES(rol.id);


CREATE TABLE ROLES 
(
  rol elemento
)
TABLESPACE ts_naturaantioquia;

ALTER TABLE ROLES
ADD CONSTRAINT nn_rol_roles CHECK (rol.nombre IS NOT NULL);

ALTER TABLE ROLES
ADD CONSTRAINT pk_id_rol_roles PRIMARY KEY ( rol.id);

CREATE TABLE PERFILES 
(
  ID_PERFIL INTEGER 
, ID_FORMULARIO INTEGER 
, INSERTAR NUMBER(1) 
, ACTUALIZAR NUMBER(1) 
, ELIMINAR NUMBER(1) 
)
TABLESPACE ts_naturaantioquia;


ALTER TABLE PERFILES
ADD CONSTRAINT nn_insertar_perfiles CHECK (INSERTAR IS NOT NULL);

ALTER TABLE PERFILES
ADD CONSTRAINT nn_actualizar_perfiles CHECK (ACTUALIZAR IS NOT NULL);

ALTER TABLE PERFILES
ADD CONSTRAINT nn_eliminar_perfiles CHECK (ELIMINAR IS NOT NULL);

ALTER TABLE PERFILES
ADD CONSTRAINT chk_boolean_insertar CHECK (INSERTAR IN (0, 1));

ALTER TABLE PERFILES
ADD CONSTRAINT chk_boolean_actualizar CHECK (ACTUALIZAR IN (0, 1));

ALTER TABLE PERFILES
ADD CONSTRAINT chk_boolean_eliminar CHECK (ELIMINAR IN (0, 1));

ALTER TABLE PERFILES
ADD CONSTRAINT pk_id_perfil_id_formulario_perfiles PRIMARY KEY (ID_PERFIL, ID_FORMULARIO);


ALTER TABLE PERFILES
ADD CONSTRAINT fk_id_perfil_perfiles
FOREIGN KEY (ID_PERFIL)
REFERENCES ROLES(rol.id);

ALTER TABLE PERFILES
ADD CONSTRAINT fk_id_formulario_perfiles
FOREIGN KEY (ID_FORMULARIO)
REFERENCES FORMULARIOS(ID_FORMULARIO);


CREATE TABLE FORMULARIOS 
(
  ID_FORMULARIO INTEGER 
, NOMBRE_FORMULARIO VARCHAR2(50) 
, NODO_PRINCIPAL NUMBER(1) 
, MODULO NUMBER(1) 
, ID_PADRE INTEGER 
, ORDEN INTEGER 
, URL VARCHAR2(100) 
)
TABLESPACE ts_naturaantioquia;

ALTER TABLE FORMULARIOS
ADD CONSTRAINT nn_nombre_formulario_formularios CHECK (NOMBRE_FORMULARIO IS NOT NULL);

ALTER TABLE FORMULARIOS
ADD CONSTRAINT nn_nodo_principal_formularios CHECK (NODO_PRINCIPAL IS NOT NULL);

ALTER TABLE FORMULARIOS
ADD CONSTRAINT nn_modulo_formularios CHECK (MODULO IS NOT NULL);

ALTER TABLE FORMULARIOS
ADD CONSTRAINT nn_orden_formularios CHECK (ORDEN IS NOT NULL);

ALTER TABLE FORMULARIOS
ADD CONSTRAINT nn_url_formularios CHECK (URL IS NOT NULL);

ALTER TABLE FORMULARIOS
ADD CONSTRAINT chk_boolean_nodo_principal CHECK (NODO_PRINCIPAL IN (0, 1));

ALTER TABLE FORMULARIOS
ADD CONSTRAINT chk_boolean_modulo CHECK (MODULO IN (0, 1));

CREATE UNIQUE INDEX idx_id_padre_orden ON FORMULARIOS (ID_PADRE, ORDEN);

ALTER TABLE FORMULARIOS
ADD CONSTRAINT pk_id_formulario_formularios PRIMARY KEY (ID_FORMULARIO);

ALTER TABLE FORMULARIOS
ADD CONSTRAINT fk_id_padre_formularios
FOREIGN KEY (ID_PADRE)
REFERENCES FORMULARIOS(ID_FORMULARIO);

--objetos
CREATE OR REPLACE TYPE US_NATURAANTIOQUIA.telefonos AS OBJECT (
        fijo  INTEGER,
        movil INTEGER
);
CREATE OR REPLACE TYPE US_NATURAANTIOQUIA.contacto AS OBJECT (
        nombre   VARCHAR2(150),
        telefono telefonos,
        correo   VARCHAR2(100)
);
CREATE OR REPLACE TYPE US_NATURAANTIOQUIA.elemento AS OBJECT (
        id     INTEGER,
        nombre VARCHAR2(50)
);

